// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmy03PtJQhusi6cYfUTXSc-ff_BkZEmQM',
    appId: '1:1088881695526:android:cfab1f983ccfddfafbffe7',
    messagingSenderId: '1088881695526',
    projectId: 'fireappmov3',
    databaseURL: 'https://fireappmov3-default-rtdb.firebaseio.com',
    storageBucket: 'fireappmov3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_uUFuH4cx4YITqBq5Dy_fjl_ULkujL0',
    appId: '1:1088881695526:web:12198ce0392a2868fbffe7',
    messagingSenderId: '1088881695526',
    projectId: 'fireappmov3',
    authDomain: 'fireappmov3.firebaseapp.com',
    databaseURL: 'https://fireappmov3-default-rtdb.firebaseio.com',
    storageBucket: 'fireappmov3.firebasestorage.app',
    measurementId: 'G-KCQB7GL4CS',
  );
}
